#ifndef ERRORCODES_H
#define ERRORCODES_H

enum DatabaseReturnMessage {
    SUCCESS = 0,
    NO_PPP_ID,
    NO_USER_ID,
    NO_PROJECT_ID,
    NO_USERNAME,
    NO_REGISTERED_STUDENTS,
    NO_USER_TYPE,
    DATABASE_QUERY_ERROR,
    UNKNOWN_ERROR,
    ALGORITHM_EXECUTE_ERROR
};

#endif // ERRORCODES_H
